# Generated by Django 3.2.23 on 2024-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240613_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulacion',
            name='impacto_publico',
            field=models.CharField(choices=[('-1', 'Sin Asignar'), ('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='factibilidad',
            field=models.CharField(choices=[('-1', 'Sin Asignar'), ('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='impacto',
            field=models.CharField(choices=[('-1', 'Sin Asignar'), ('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR')], default='-1', max_length=2),
        ),
    ]
