# Generated by Django 3.2.23 on 2024-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240613_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulacion',
            old_name='escala',
            new_name='comentarios',
        ),
    ]
