# Generated by Django 3.2.23 on 2024-06-13 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_escala_regulacion_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_activacion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='regulacion',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
