# Generated by Django 3.2.23 on 2024-06-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240613_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='informacion',
        ),
    ]
