# Generated by Django 3.2.23 on 2024-06-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nombre_comentario_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile'),
        ),
        migrations.AddField(
            model_name='regulacion',
            name='estado_tramite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='esg',
            field=models.CharField(choices=[('0', 'IMPLEMENTACION'), ('1', 'E'), ('2', 'S'), ('3', 'G'), ('4', 'N/A'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='factibilidad',
            field=models.CharField(choices=[('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='impacto',
            field=models.CharField(choices=[('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='impacto_publico',
            field=models.CharField(choices=[('0', 'IMPLEMENTACION'), ('1', 'BAJO'), ('2', 'MEDIO'), ('3', 'ALTO'), ('4', 'SIN DEFINIR'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='priorizacion',
            field=models.CharField(choices=[('0', 'POR DEFINIR'), ('1', 'INCIDENCIA'), ('2', 'INFORMAR'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
        migrations.AlterField(
            model_name='regulacion',
            name='servicio',
            field=models.CharField(choices=[('0', 'S'), ('1', 'M'), ('2', 'L'), ('-1', 'SIN ASIGNAR')], default='-1', max_length=2),
        ),
    ]
