# Generated by Django 3.2.23 on 2024-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240619_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulacion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
