# Generated by Django 3.2.23 on 2024-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_regulacion_fecha_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
