# Generated by Django 3.2.23 on 2024-06-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_regulacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulacion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
