# Generated by Django 3.2.23 on 2025-05-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_cambiar_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, default='media/account_avatar.png', null=True, upload_to='media/')),
                ('background', models.ImageField(blank=True, default='media/bg-app.jpg', null=True, upload_to='media/')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('flow_sync', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_usuario',
        ),
    ]
