# Generated by Django 3.2.23 on 2025-05-21 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20250521_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'Publicador'), ('2', 'Editor'), ('3', 'Lector')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='auth.user'),
            preserve_default=False,
        ),
    ]
